title: "Brian Zebosi"
author: "Brian Zebosi"
description: "Iowa State Unversity"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_social: true          # show site description and social links in the footer
show_excerpts: false        # show article excerpts on the home page
show_frame: false          # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header

# Menu

navigation:
  - {title: "CV", url: "/katie.pdf", icon: home}
  - {title: "Research", file: "blog.md"}
  - {title: "Blog", file: "blog.md"}
Github: "https://github.com/bzebosi"


 
  
  social-network-links:
  email: "zebosibrian@gmail.com"
  github: "bzebosi"
  twitter: "zebrimas"
  
  # Select which share links to show in posts
share-links-active:
  twitter: true
#  facebook: true
  google: false
  linkedin: true
  

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
